export default {
    SHOW_LOADING : "SHOW_LOADING",
    UPDATE_USER : "UPDATE_USER",
    SET_SERVICE_WORKER_READY : "SET_SERVICE_WORKER_READY",
    
    TOGGLE_PROFILE_POPUP: "TOGGLE_PROFILE_POPUP",
    TOGGLE_NOTIFICATION_POPUP: "TOGGLE_NOTIFICATION_POPUP",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR"
}