/**
 * Created by wardo on 3/16/2018.
 */
export default {
    WIDGET_FILTER_SET_WEEK: "WIDGET_FILTER_SET_WEEK",
    WIDGET_FILTER_SET_YEAR: "WIDGET_FILTER_SET_YEAR",
    WIDGET_FILTER_SET_UNIT: "WIDGET_FILTER_SET_UNIT",
    WIDGET_FILTER_SET_PERIOD: "WIDGET_FILTER_SET_PERIOD"
}