/**
 * Created by wardo on 3/19/2018.
 */
export default {
    TOTAL_STOCK_BAR_CHART_START_FETCH: "TOTAL_STOCK_BAR_CHART_START_FETCH",
    TOTAL_STOCK_BAR_CHART_FETCH_DATA: "TOTAL_STOCK_BAR_FETCH_DATA",
    TOTAL_STOCK_BAR_CHART_RECEIVED_DATA: "TOTAL_STOCK_BAR_RECEIVED_DATA"
}